# Generated by Django 3.0.3 on 2020-03-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar_fly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
